process.env.DATABASE_URL = ':memory:'
process.env.NODE_ENV = 'test'
process.env.APP_ID = process.env.APP_SECRET = 'troll'
process.env.TTN_URL = 'http://localhost:9000'
process.env.TASK_API = 'http://localhost:9000/task'
